### ISSUE TITLE
Sending a message from Discord when in-game, states a [g] message instead of a [dg] message

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/DiscordPlugin#15]
![image](https://cloud.githubusercontent.com/assets/18705807/20952151/5f6ddf2a-bbf8-11e6-9fb9-6ff4aa2fb270.png)

**Comment by NorbiPeti** [comment]
Oh well, the DiscordPlayerSender implements Player, so the chat plugin assumes it's an ingame player. The only solution I can think of (at least what seems to be the fastest) is to check against CraftPlayer, which will make it version-dependent. Though we can update it easily so that shouldn't be an issue.

**Comment by NorbiPeti** [comment]
Actually, I solved it (if I solved it) with 3 commits from 3 repositories. /shrug

https://github.com/TBMCPlugins/ButtonCore/commit/381739456c405474d6133111fc9dd8db46f329e8
https://github.com/TBMCPlugins/DiscordPlugin/commit/6f5bca8993546fd9aab6372f1a129a5a2d03a97e
https://github.com/TBMCPlugins/DiscordPlugin/commit/6f5bca8993546fd9aab6372f1a129a5a2d03a97e
